import { Header } from '@/components/ui/';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Navigation } from '@/components/ui/';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const nav = [
    { label: 'Offers', link: '/' },
    { label: 'Add Offer', link: '/add' },
    { label: 'About', link: '/about' },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header titel="Jobboard">
            <Navigation nav={nav} />
          </Header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
